-- Backup of users before DB reset
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (1, 'kira_wolf', 'kira@return.game', 'hash_001_kw', '2026-03-01 16:00:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (2, 'darius_03', 'darius@return.game', 'hash_002_dr', '2026-03-02 17:15:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (3, 'mira_shade', 'mira@return.game', 'hash_003_ms', '2026-03-03 15:30:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (4, 'valen_iron', 'valen@return.game', 'hash_004_vi', '2026-03-05 20:45:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (5, 'nyx_runner', 'nyx@return.game', 'hash_005_nr', '2026-03-08 00:20:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (6, 'elys_oak', 'elys@return.game', 'hash_006_eo', '2026-03-10 14:00:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (7, 'thane_grim', 'thane@return.game', 'hash_007_tg', '2026-03-13 04:10:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (8, 'selene_v', 'selene@return.game', 'hash_008_sv', '2026-03-15 22:30:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (9, 'corvo_x', 'corvo@return.game', 'hash_009_cx', '2026-03-18 19:00:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (10, 'ilya_starr', 'ilya@return.game', 'hash_010_is', '2026-03-21 01:50:00', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (11, 'OMEGA', 'juanbrinez1111@gmail.com', '$2b$10$cq4cc4RvU8hFnH6rePV87eG7v7QR4MMQhr7ftyxjQwfSztcHc8lY6', '2026-05-18 04:16:45', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (17, 'paulo', 'a01787207@tec.mx', '$2b$10$RGrGgNHJOLhh6IA0PrfxledImKuA/WidqYyFoDFH3FbuLkhXsQrU2', '2026-06-05 14:07:59', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);
INSERT INTO users (id, username, email, password_hash, created_at, failed_attempts, lock_until) VALUES (18, 'testuser123', 'test@test.com', '$2b$10$HqLzfJogBdo295Ecjv4h9ODBN85nEy0vU4jWkinDERs.xJaTORMti', '2026-06-08 17:38:40', 0, NULL) ON DUPLICATE KEY UPDATE username=VALUES(username);